# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 529bb3b1204c7ddd5957b8e47c39ec1d1d84e10925a225af42cefdc9a17e0e256cd013cb496d593f6974e8ae13e4e3605f2aa6d118d7ff35fb166a7c171830c3

test:
  secret_key_base: a0e665d69d13d52a5d11dfaf3f5fc6622425cc58efb97c66996bcd165a4b8c3e3db1ba4542945950a9171096ddb11c52c3aed8f5dd3e5010abe5397d09b02113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
